---
- name: Fully provision Cafco production server
  hosts: web
  become: yes
  vars_files:
    - ../group_vars/all.yml
  roles:
    - common
    - harden
    - nodejs
    - nginx
    - certbot
    - pm2
    - app
    - backup
